
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-15
owner: ucsb-cs156-s25
repo_name: team01-s25-15
pull_requests: [{"author":{"id":"MDQ6VXNlcjg1MDA2ODI4","is_bot":false,"login":"perryjirakit","name":""},"headRefName":"pt-put-for-RecommendationRequest-table","number":72,"title":"Pt put for recommendation request table","url":"https://github.com/ucsb-cs156-s25/team01-s25-15/pull/72"},{"author":{"id":"MDQ6VXNlcjg1MDA2ODI4","is_bot":false,"login":"perryjirakit","name":""},"headRefName":"pt-RecommendationRequest-get-by-id","number":71,"title":"Pt - add GET by id for RecommendationrRequest","url":"https://github.com/ucsb-cs156-s25/team01-s25-15/pull/71"},{"author":{"id":"MDQ6VXNlcjg1MDA2ODI4","is_bot":false,"login":"perryjirakit","name":""},"headRefName":"pt-create-RecommendationRequest-controller","number":69,"title":"Pt create recommendation request controller, add GET /all and POST methods","url":"https://github.com/ucsb-cs156-s25/team01-s25-15/pull/69"},{"author":{"id":"U_kgDOB9EidQ","is_bot":false,"login":"davidduena","name":""},"headRefName":"dd-delete-for-helprequest","number":63,"title":"Dd delete for helprequest","url":"https://github.com/ucsb-cs156-s25/team01-s25-15/pull/63"}]
