
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-15
owner: ucsb-cs156-s25
repo_name: team01-s25-15
pull_requests: [{"author":{"id":"U_kgDOCM79zg","is_bot":false,"login":"Tyler-W0ng","name":""},"headRefName":"tw-delete-for-MenuItemReview-table","number":51,"title":"Tw delete for menu item review table","url":"https://github.com/ucsb-cs156-s25/team01-s25-15/pull/51"},{"author":{"id":"U_kgDOB9EidQ","is_bot":false,"login":"davidduena","name":""},"headRefName":"dd-HelpRequest-create-controller","number":49,"title":"dd create HelpRequests controller","url":"https://github.com/ucsb-cs156-s25/team01-s25-15/pull/49"}]
