
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-15
owner: ucsb-cs156-s25
repo_name: team01-s25-15
pull_requests: [{"author":{"id":"U_kgDOB9EidQ","is_bot":false,"login":"davidduena","name":""},"headRefName":"dd-delete-for-helprequest","number":63,"title":"Dd delete for helprequest","url":"https://github.com/ucsb-cs156-s25/team01-s25-15/pull/63"},{"author":{"id":"U_kgDOB9EidQ","is_bot":false,"login":"davidduena","name":""},"headRefName":"dd-put-for-HelpRequest","number":62,"title":"Dd put for help request","url":"https://github.com/ucsb-cs156-s25/team01-s25-15/pull/62"},{"author":{"id":"U_kgDOB9EidQ","is_bot":false,"login":"davidduena","name":""},"headRefName":"dd-HelpRequest-get-by-id","number":61,"title":"Dd - add GET id for HelpRequest","url":"https://github.com/ucsb-cs156-s25/team01-s25-15/pull/61"},{"author":{"id":"U_kgDOB9EidQ","is_bot":false,"login":"davidduena","name":""},"headRefName":"dd-HelpRequest-create-controller","number":49,"title":"dd create HelpRequests controller","url":"https://github.com/ucsb-cs156-s25/team01-s25-15/pull/49"}]
