
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-15
owner: ucsb-cs156-s25
repo_name: team01-s25-15
pull_requests: [{"author":{"id":"U_kgDOB9EidQ","is_bot":false,"login":"davidduena","name":""},"headRefName":"dd-HelpRequest-create-controller","number":49,"title":"dd create HelpRequests controller","url":"https://github.com/ucsb-cs156-s25/team01-s25-15/pull/49"},{"author":{"id":"U_kgDOCM79zg","is_bot":false,"login":"Tyler-W0ng","name":""},"headRefName":"tw-MenuItemReviews-get-by-id","number":48,"title":"Tw - add GET by id for MenuItemReviews","url":"https://github.com/ucsb-cs156-s25/team01-s25-15/pull/48"},{"author":{"id":"U_kgDOCVG6FA","is_bot":false,"login":"BryceInouye","name":""},"headRefName":"bi-Articles-create-db","number":47,"title":"Create db table for Articles","url":"https://github.com/ucsb-cs156-s25/team01-s25-15/pull/47"},{"author":{"id":"U_kgDOB9EidQ","is_bot":false,"login":"davidduena","name":""},"headRefName":"dd-HelpRequest-create-db","number":46,"title":"dd - database table for HelpRequest","url":"https://github.com/ucsb-cs156-s25/team01-s25-15/pull/46"},{"author":{"id":"U_kgDOCM79zg","is_bot":false,"login":"Tyler-W0ng","name":""},"headRefName":"tw-create-MenuItemReview-controller","number":45,"title":"Tw create menu item review controller","url":"https://github.com/ucsb-cs156-s25/team01-s25-15/pull/45"},{"author":{"id":"U_kgDOCJYDtQ","is_bot":false,"login":"Esomevath","name":"Lucas Havemose"},"headRefName":"lh-UCSBDiningCommonsMenuItem-create-db","number":44,"title":"UCSBDiningCommonsMenuItem create database","url":"https://github.com/ucsb-cs156-s25/team01-s25-15/pull/44"},{"author":{"id":"U_kgDOCM79zg","is_bot":false,"login":"Tyler-W0ng","name":""},"headRefName":"tw-MenuItemReview-create-db","number":43,"title":"tw - create database table for MenuItemReviews","url":"https://github.com/ucsb-cs156-s25/team01-s25-15/pull/43"}]
